### ISSUE TITLE
direct.image, agency.image에 데이터가 없을 때 예외처리가 부족합니다

### ISSUE THREAD

**Issue by sookcha** [heejongahn/tinkerbell-template#1]
안녕하세요, 우선 이렇게 멋진 프로젝트 만들어 주셔서 감사합니다.
지금 https://github.com/heejongahn/tinkerbell-template/blob/8f3bca213ceb345da77ca718a4689466178b9c4b/src/remotes/index.ts#L35 이 라인에 예외처리가 되어 있지 않아 문제가 발생해서 이슈 남깁니다. direct.image와 agency.image에 값이 존재하지 않을 경우 프로그램이 그대로 뻗게 됩니다. 코드를 아직 덜 봤지만, 가장 간단하게는 `houses` 를 만드는 반복문에서 해당 값이 있는지 체크하는 식으로 해결할 수 있을 것 같습니다.

**Comment by heejongahn** [comment]
https://github.com/heejongahn/tinkerbell-template/pull/2#issuecomment-565732467
